[package]
name = "to-do-app"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gtk4 = "0.8.0"

[build-dependencies]
glib-build-tools = "0.19.0"
